// ── Static sample data ──────────────────────────────────────────────────
// Build-time imports of the artifacts written to main.py's OUTPUT_DIR.
// Keeping every generated input rooted there means rerunning the backend
// updates the next dev-server reload/build without a manual copy. There is
// no backend API yet, so these remain JSON module imports rather than fetches.
//
// Derived once here rather than per view: both the app shell and the
// anchored-graph view read the same trace, and rebuilding the branch panels
// or the explorer tree per mount would give them different object identities.

import {
  flattenedRaw,
  fullGraphRaw,
  phaseTreeRaw,
  topicClusterRaw,
  topicOperationsRaw,
  opseqVisualisationsRaw,
} from "virtual:flowmap-data";
import type { FlowGraph, PhaseTree } from "../types/flowmap";
import type { TopicCluster, TopicOperation } from "../types/topics";
import { indexNodesById, buildExplorerTree } from "../lib/graph";
import { buildBranchPanels } from "../lib/branches";
import { sortTopics } from "../lib/topics";

export const GRAPH = flattenedRaw as unknown as FlowGraph;
export const FULL_GRAPH = fullGraphRaw as unknown as FlowGraph;
export const PHASE_TREE = phaseTreeRaw as unknown as PhaseTree;
export const PHASES = PHASE_TREE.phases;
export const ROOT_ID = GRAPH.rootId!;
export const NODES_BY_ID = indexNodesById(GRAPH.nodes);
export const EXPLORER_TREE = buildExplorerTree(GRAPH.nodes);

// Every switchable fork in the trace. All of them come from the backend's
// own branch groups -- IF/TRY for conditionals, DISPATCH for a call site
// with more than one real implementation. Only one arm of each is on screen
// at a time; see visibleGraphSelection.
export const PANELS = buildBranchPanels(GRAPH, ROOT_ID);

// "data" edges are a phase-discovery input, not control flow -- they answer
// "these two calls touch the same value", which is not a step the reader
// takes through the trace. A loop back-edge is likewise retained as CFG
// metadata but is not a second forward process step. Both are excluded
// from the linear view here; the pipeline still emits and uses them.
export const FLOW_EDGES = GRAPH.edges.filter((e) => e.type !== "data" && !e.loopBack);

const GENERATED_TOPICS = topicClusterRaw as unknown as TopicCluster[];

// Generated by backend/src/flowmap/main.py from its opseq assignment and
// label outputs. The frontend intentionally does not own a second copy.
const GENERATED_OPERATIONS_BY_TOPIC = topicOperationsRaw as Record<string, TopicOperation[]>;

export interface GraphVisualisation {
  graph: FlowGraph;
  phaseTree: PhaseTree;
  rootMethodFullName?: string;
  memberMethodFullNames?: string[];
}

export function graphVisualisation(graph: FlowGraph, phaseTree: PhaseTree): GraphVisualisation {
  return { graph, phaseTree };
}

export const ANCHORED_VISUALISATION = graphVisualisation(GRAPH, PHASE_TREE);

// Generated alongside topic_operations.json. Each root id resolves to the
// exact flattened graph and phase tree the shared graph view needs.
export const OPSEQ_VISUALISATIONS = opseqVisualisationsRaw as Record<string, GraphVisualisation>;

// Older exports omitted roots for which classification returned no topic.
// Reconstruct that bucket from the complete opseq index so Topic Discovery
// never silently loses an operation. New backend exports provide the same
// entries directly under HDBSCAN's noise label (-1).
const generatedUnclustered = GENERATED_OPERATIONS_BY_TOPIC["-1"] ?? [];
const assignedOpseqIds = new Set(
  Object.values(GENERATED_OPERATIONS_BY_TOPIC).flatMap((operations) =>
    operations.map((operation) => operation.id)
  ),
);
const reconstructedUnclustered: TopicOperation[] = Object.entries(OPSEQ_VISUALISATIONS)
  .filter(([id]) => !assignedOpseqIds.has(id))
  .map(([id, visualisation]) => {
    const rootMethodFullName = visualisation.rootMethodFullName
      ?? visualisation.graph.entryPoint
      ?? id;
    return {
      id,
      label: rootMethodFullName,
      rootMethodFullName,
      similarity: 0,
    };
  });

export const OPERATIONS_BY_TOPIC: Record<string, TopicOperation[]> = {
  ...GENERATED_OPERATIONS_BY_TOPIC,
  "-1": [...generatedUnclustered, ...reconstructedUnclustered]
    .sort((a, b) => a.label.localeCompare(b.label)),
};

// Unclustered is an opseq destination even when class clustering happened
// to produce no noise cluster, so guarantee that it is always selectable.
export const TOPICS = sortTopics(
  GENERATED_TOPICS.some((topic) => topic.label === -1)
    ? GENERATED_TOPICS
    : [...GENERATED_TOPICS, {
      label: -1,
      member_full_names: [],
      statistical_terms: [],
      readme_paths: [],
    }],
);

export interface OpseqChoice {
  id: string;
  label: string;
  rootMethodFullName: string;
}

const operationMetadataById = new Map<string, TopicOperation>();
for (const operations of Object.values(OPERATIONS_BY_TOPIC)) {
  for (const operation of operations) {
    if (!operationMetadataById.has(operation.id)) operationMetadataById.set(operation.id, operation);
  }
}

const opseqIdsByMethod = new Map<string, string[]>();
for (const [id, visualisation] of Object.entries(OPSEQ_VISUALISATIONS)) {
  // New exports carry unfiltered membership explicitly. The graph scan keeps
  // older generated artifacts usable until the backend is rerun.
  const memberMethods = visualisation.memberMethodFullNames
    ?? visualisation.graph.nodes.flatMap((node) =>
      node.type === "entry" && node.calleeFullName ? [node.calleeFullName] : []
    );
  for (const method of new Set(memberMethods)) {
    const ids = opseqIdsByMethod.get(method);
    if (ids) ids.push(id);
    else opseqIdsByMethod.set(method, [id]);
  }
}

export function opseqChoicesForMethod(methodFullName: string): OpseqChoice[] {
  return (opseqIdsByMethod.get(methodFullName) ?? []).map((id) => {
    const visualisation = OPSEQ_VISUALISATIONS[id];
    const metadata = operationMetadataById.get(id);
    const rootMethodFullName = visualisation?.rootMethodFullName
      ?? metadata?.rootMethodFullName
      ?? visualisation?.graph.entryPoint
      ?? id;
    return {
      id,
      label: metadata?.label ?? rootMethodFullName,
      rootMethodFullName,
    };
  }).sort((a, b) => a.label.localeCompare(b.label));
}

export function methodParticipatesInOpseq(methodFullName: string): boolean {
  return opseqIdsByMethod.has(methodFullName);
}
