// ── Static sample data ──────────────────────────────────────────────────
// Build-time imports of the artifacts written to main.py's OUTPUT_DIR.
// Keeping every generated input rooted there means rerunning the backend
// updates the next dev-server reload/build without a manual copy. There is
// no backend API yet, so these remain JSON module imports rather than fetches.
//
// Derived once here rather than per view: both the app shell and the
// anchored-graph view read the same trace, and rebuilding the branch panels
// or the explorer tree per mount would give them different object identities.

import {
  fullGraphRaw,
  topicClusterRaw,
  topicOperationsRaw,
  opseqVisualisationsRaw,
} from "virtual:flowmap-data";
import type { FlowGraph, PhaseTree } from "../types/flowmap";
import type { TopicCluster, TopicOperation } from "../types/topics";
import { sortTopics } from "../lib/topics";

export const FULL_GRAPH = fullGraphRaw as unknown as FlowGraph;

const GENERATED_TOPICS = topicClusterRaw as unknown as TopicCluster[];

// Generated by backend/src/flowmap/main.py from its opseq assignment and
// label outputs. The frontend intentionally does not own a second copy.
const GENERATED_OPERATIONS_BY_TOPIC = topicOperationsRaw as Record<string, TopicOperation[]>;

export interface GraphVisualisation {
  graph: FlowGraph;
  phaseTree: PhaseTree;
  rootMethodFullName?: string;
  memberMethodFullNames?: string[];
}

export function graphVisualisation(graph: FlowGraph, phaseTree: PhaseTree): GraphVisualisation {
  return { graph, phaseTree };
}

// Generated alongside topic_operations.json. Each root id resolves to the
// exact flattened graph and phase tree the shared graph view needs.
export const OPSEQ_VISUALISATIONS = opseqVisualisationsRaw as Record<string, GraphVisualisation>;
const EMPTY_VISUALISATION = graphVisualisation(
  { nodes: [], edges: [] },
  { entryPoint: "", phases: [] },
);
export const ANCHORED_VISUALISATION =
  Object.values(OPSEQ_VISUALISATIONS)[0] ?? EMPTY_VISUALISATION;
export const GRAPH = ANCHORED_VISUALISATION.graph;

// Class-clustering noise (-1) is not an operation topic. Also normalize
// older top-k exports by retaining only each opseq's highest-similarity
// assignment, so stale artifacts cannot show one operation under two topics.
const highestAssignmentByOpseq = new Map<
  string,
  { topicLabel: string; operation: TopicOperation }
>();
for (const [topicLabel, operations] of Object.entries(GENERATED_OPERATIONS_BY_TOPIC)) {
  if (topicLabel === "-1") continue;
  for (const operation of operations) {
    const current = highestAssignmentByOpseq.get(operation.id);
    if (!current || operation.similarity > current.operation.similarity) {
      highestAssignmentByOpseq.set(operation.id, { topicLabel, operation });
    }
  }
}

export const OPERATIONS_BY_TOPIC: Record<string, TopicOperation[]> = {};
for (const { topicLabel, operation } of highestAssignmentByOpseq.values()) {
  (OPERATIONS_BY_TOPIC[topicLabel] ??= []).push(operation);
}
for (const operations of Object.values(OPERATIONS_BY_TOPIC)) {
  operations.sort((a, b) => a.label.localeCompare(b.label));
}
export const ALLOCATED_OPSEQ_COUNT = highestAssignmentByOpseq.size;

export const TOPICS = sortTopics(
  GENERATED_TOPICS.filter((topic) => topic.label !== -1),
);

export interface OpseqChoice {
  id: string;
  label: string;
  rootMethodFullName: string;
}

const operationMetadataById = new Map<string, TopicOperation>();
for (const operations of Object.values(OPERATIONS_BY_TOPIC)) {
  for (const operation of operations) {
    if (!operationMetadataById.has(operation.id)) operationMetadataById.set(operation.id, operation);
  }
}

const opseqIdsByMethod = new Map<string, string[]>();
for (const [id, visualisation] of Object.entries(OPSEQ_VISUALISATIONS)) {
  // New exports carry unfiltered membership explicitly. The graph scan keeps
  // older generated artifacts usable until the backend is rerun.
  const memberMethods = visualisation.memberMethodFullNames
    ?? visualisation.graph.nodes.flatMap((node) =>
      node.type === "entry" && node.calleeFullName ? [node.calleeFullName] : []
    );
  for (const method of new Set(memberMethods)) {
    const ids = opseqIdsByMethod.get(method);
    if (ids) ids.push(id);
    else opseqIdsByMethod.set(method, [id]);
  }
}

export function opseqChoicesForMethod(methodFullName: string): OpseqChoice[] {
  return (opseqIdsByMethod.get(methodFullName) ?? []).map((id) => {
    const visualisation = OPSEQ_VISUALISATIONS[id];
    const metadata = operationMetadataById.get(id);
    const rootMethodFullName = visualisation?.rootMethodFullName
      ?? metadata?.rootMethodFullName
      ?? visualisation?.graph.entryPoint
      ?? id;
    return {
      id,
      label: metadata?.label ?? rootMethodFullName,
      rootMethodFullName,
    };
  }).sort((a, b) => a.label.localeCompare(b.label));
}

export function methodParticipatesInOpseq(methodFullName: string): boolean {
  return opseqIdsByMethod.has(methodFullName);
}
