// ── Static sample data ──────────────────────────────────────────────────
// Build-time imports of the artifacts written to main.py's OUTPUT_DIR.
// Keeping every generated input rooted there means rerunning the backend
// updates the next dev-server reload/build without a manual copy. There is
// no backend API yet, so these remain JSON module imports rather than fetches.
//
// Topic metadata is normalized once here so every topic view uses the same
// operation assignment and ordering.

import { topicClusterRaw, topicOperationsRaw } from "virtual:flowmap-data";
import type { TopicCluster, TopicOperation } from "../types/topics";
import { sortTopics } from "../lib/topics";

export { GRAPH_BUNDLE, FILTERED_GRAPH_DATA } from "./filteredGraph";

const GENERATED_TOPICS = topicClusterRaw as unknown as TopicCluster[];

// Generated by backend/src/flowmap/main.py from its opseq assignment and
// label outputs. The frontend intentionally does not own a second copy.
const GENERATED_OPERATIONS_BY_TOPIC = topicOperationsRaw as Record<string, TopicOperation[]>;

// Normalize older top-k exports by retaining only each opseq's
// highest-similarity assignment, so stale artifacts cannot show one operation
// under two discovered topics. The -1 bucket is added separately below.
const highestAssignmentByOpseq = new Map<
  string,
  { topicLabel: string; operation: TopicOperation }
>();
for (const [topicLabel, operations] of Object.entries(GENERATED_OPERATIONS_BY_TOPIC)) {
  if (topicLabel === "-1") continue;
  for (const operation of operations) {
    const current = highestAssignmentByOpseq.get(operation.id);
    if (!current || operation.similarity > current.operation.similarity) {
      highestAssignmentByOpseq.set(operation.id, { topicLabel, operation });
    }
  }
}

export const OPERATIONS_BY_TOPIC: Record<string, TopicOperation[]> = {};
for (const { topicLabel, operation } of highestAssignmentByOpseq.values()) {
  (OPERATIONS_BY_TOPIC[topicLabel] ??= []).push(operation);
}

// The backend retains operations with no topic assignment under -1. Surface
// them as a final Unassigned group, without duplicating an operation that also
// appears in an older mixed assignment export.
const unassignedOperations = (GENERATED_OPERATIONS_BY_TOPIC["-1"] ?? [])
  .filter((operation) => !highestAssignmentByOpseq.has(operation.id));
if (unassignedOperations.length > 0) {
  OPERATIONS_BY_TOPIC["-1"] = unassignedOperations;
}
for (const operations of Object.values(OPERATIONS_BY_TOPIC)) {
  operations.sort((a, b) => a.label.localeCompare(b.label));
}
export const ALLOCATED_OPSEQ_COUNT = highestAssignmentByOpseq.size + unassignedOperations.length;

const discoveredTopics = GENERATED_TOPICS.filter((topic) => topic.label !== -1);
const unassignedTopic: TopicCluster = {
  label: -1,
  member_full_names: [],
  statistical_terms: [],
  readme_paths: [],
};

export const DISCOVERED_TOPIC_COUNT = discoveredTopics.length;
export const TOPICS = sortTopics(
  unassignedOperations.length > 0
    ? [...discoveredTopics, unassignedTopic]
    : discoveredTopics,
);
