"""Configuration shared by every LLM query path."""

LLM_MAX_ATTEMPTS = 3
LLM_MAX_CONCURRENT_REQUESTS = 4
LLM_TARGET_INPUT_TOKENS = 10_000
LLM_TARGET_OUTPUT_TOKENS = 2_048
LLM_EXPECTED_OUTPUT_CHARS_PER_ITEM = 180
LLM_BATCH_SIZES = (32, 32, 1)
